### PR TITLE
Fix socket leak

### LINKED ISSUE #156: Socket file descriptor leak
### Summary
My NodeJS app launches hundreds of GET requests in parallel using Axios 0.21.1. Noticed that socket file descriptors are not getting released. After a few requests the count of open socket file descriptors continues to increase rapidly. This poses an immediate problem in environments such as AWS Lambda which imposes a limit of 1024 open file descriptors per Node process. I've tracked down the problem to follow-redirects, I'm using version 1.13.3.

I've been able to reproduce this issue consistently.

1. Open a Node interactive session, `node -i` in the parent folder of the `follow-redirects` source code.
2. Run once command `ps -ef| grep 'node -i' | grep -v grep | awk -F" " '{cmd="lsof -P -i -n | grep "$2""; system(cmd)}'` on MacOs, or `ps -ef| grep 'node -i' | grep -v grep | awk -F" " '{cmd="ls -l /proc/"$2"/fd"; system(cmd)}'` on Linux. There should be no output at all, which means there are no open file descriptors.
3. Copy/paste the below Node.js script and run many times (like 10 times or more),
```
var http = require('./').http
var req = http.request({
  host: 'www.sho.com',
  path: '/site/image-bin/images/93_0_3497874/93_0_3497874_98_711x400.jpg'
  }, response => {
  console.log(response.responseUrl);
});
req.setTimeout(15000, function handleRequestTimeout() {
        req.abort();
  });
req.end();
```
4. Run repeatedly command from step number 2 above. Notice all the open file descriptors. Even after waiting a bit the number of open file descriptors does not go down. 

This issue is what causes [issue #3217](https://github.com/axios/axios/issues/3217) in Axios

If you want you can try the same steps above but with my PR #157 fix, and notice the file descriptor count drops quickly, specifically because the socket timeout is taking care of cleaning them up in a timely manner.

### PR DESCRIPTION
**Pull request by joquijada**
fixes #156

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
@joquijada Thanks! I simplified the code a bit.
Does this work okay for you still?

**Comment by RubenVerborgh** [comment]
My problem with this, however, is that it only sets the timeout on the first socket. Given that the request might be redirected, there can be multiple sockets.

**Comment by joquijada** [comment]
> @joquijada Thanks! I simplified the code a bit.
> Does this work okay for you still?

Trying it out now.

**Comment by joquijada** [comment]
> My problem with this, however, is that it only sets the timeout on the first socket. Given that the request might be redirected, there can be multiple sockets.

Hm, let me analyze the code in more detail, thanks.

File: index.js [hunk 1]
```diff
@@ -156,15 +156,22 @@ RedirectableRequest.prototype.setTimeout = function (msecs, callback) {
     this.on("timeout", callback);
   }
 
+  function setSocketTimeout(socket) {
```
Comment (joquijada) [inline index.js:159]: This function has to be defined locally here as opposed to globally just to have access to the  `msecs` argument passed by the client code.
Moreover the logic to set the socket timeout is refactored into its own method to be able to serve redirect requests which don't need the other `startTimer()` logic.

File: index.js [hunk 2]
```diff
@@ -156,15 +156,22 @@ RedirectableRequest.prototype.setTimeout = function (msecs, callback) {
...
+    socket.removeListener("timeout", socket.destroy);
```
Comment (joquijada) [inline index.js:160]: This `socket.removeListener("timeout", socket.destroy);` is here because this method gets called twice for the first request. This way we avoid adding redundant `timeout` listeners to the first request.

File: index.js [hunk 3]
```diff
@@ -180,14 +187,15 @@ RedirectableRequest.prototype.setTimeout = function (msecs, callback) {
...
-    startTimer();
+    startTimer(this.socket);
   }
   else {
     this._currentRequest.once("socket", startTimer);
   }
 
   this.once("response", clearTimer);
   this.once("error", clearTimer);
+  this.on("socket", setSocketTimeout);
```
Comment (joquijada) [inline index.js:198]: A side effect of this is that `setSocketTimeout()` gets called twice for the first request. We deal with that, see comment above.

**Review by joquijada — COMMENTED** [review]
> My problem with this, however, is that it only sets the timeout on the first socket. Given that the request might be redirected, there can be multiple sockets.

I've pushed a new commit to deal with redirect requests (I.e. requests 2 and above)

File: index.js (hunk 3 above)
Comment (RubenVerborgh) [reply index.js:198]: Can't we wrap this in an `if` statement then?

Comment (joquijada) [reply index.js:201]: Something [like this](https://github.com/follow-redirects/follow-redirects/pull/157/commits/aa476d61a2ca3b6971f12b5db98bf8cad33267e6)?

Comment (joquijada) [reply index.js:203]: > Can't we wrap this in an `if` statement then?

Hello, any comments on my latest commit? Thanks.

**Comment by RubenVerborgh** [comment]
Thanks a lot!
