### PR TITLE
Fix setTimout handler

### LINKED ISSUE #106: setTimeout callback not triggered after redirect
Timeouts aren't working if they occur after a redirect.  It seems like the `timeout` event is correctly emitted and bubbled up, but the `setTimeout` callback isn't called.

Will PR a failing test.

### PR DESCRIPTION
**Pull request by cavis**
Fixes #106.

Any callback passed for [`setTimeout`](https://github.com/nodejs/node/blob/v8.10.0/lib/_http_client.js#L708) weren't being called after a redirect.

This PR: 
- [x] Overrides the `RedirectableRequest#setTimeout` method to bind the callback to the `timeout` event
- [x] Start a manual `setTimeout` to manually emit the `timeout` event
- [x] Cancel the timer on response or error

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks for taking this on @cavis!

I would, however, propose to maintain the original semantics: when a timeout of x is passed to `request`, then `request` should not take longer than x milliseconds.

Warning: pedantic comments forthcoming 🙂

File: index.js [hunk 1]
```diff
@@ -30,6 +30,7 @@ function RedirectableRequest(options, responseCallback) {
   this._redirects = [];
   this._requestBodyLength = 0;
   this._requestBodyBuffers = [];
+  this._timeoutMsecs = 0;
```
Comment (RubenVerborgh) [inline index.js]: this one can go

**Comment by cavis** [comment]
Yeah, I was trying to think of how to accomplish that.  Set an initial timestamp on the first request, and decrement the timeoutMsecs after each call i suppose?

File: index.js [hunk 2]
```diff
@@ -147,10 +148,19 @@ RedirectableRequest.prototype.removeHeader = function (name) {
   this._currentRequest.removeHeader(name);
 };
 
+// Re-bind timeout handler to all subsequent requests
+RedirectableRequest.prototype.setTimeout = function (msecs, callback) {
+  this._timeoutMsecs = msecs;
+  if (callback) {
+    this.once("timeout", callback);
+  }
+  return this._currentRequest.setTimeout(msecs);
```
Comment (RubenVerborgh) [inline index.js]: We might want to mirror [this code](https://github.com/nodejs/node/blob/v11.9.0/lib/_http_outgoing.js#L182-L193), except that we use the global function `setTimeout` instead of `socket.setTimeout`, storing the return value as `this._timeout` or so. When we reach the timeout, the current request should be aborted (without emitting the abort event) and the timeout event should be fired.
If the request succeeds before timeout, the timeout handler should be canceled.

If a new timeout value is set, we should clear the previous one.

File: index.js [hunk 3]
```diff
@@ -186,6 +196,12 @@ RedirectableRequest.prototype._performRequest = function () {
         nativeProtocol.request(this._options, this._onNativeResponse);
   this._currentUrl = url.format(this._options);
 
+  // Rebind timeout to current request - any emitted "timeout" event will
+  // bubble up to the top level callback in RedirectableRequest#setTimeout
+  if (this._timeoutMsecs) {
+    this._currentRequest.setTimeout(this._timeoutMsecs);
+  }
```
Comment (RubenVerborgh) [inline index.js]: would not be needed anymore then

File: test/lib/util.js [hunk 4]
```diff
@@ -27,6 +27,14 @@ function concatJson(resolve, reject) {
...
 }
 
+function delaysJson(ms, json) {
+  return function (req, res) {
+    setTimeout(function () {
+      res.json(json);
+    }, ms);
+  };
+}
+
```
Comment (RubenVerborgh) [inline test/lib/util.js]: this function is only used once, so should not be in reusable util

File: test/lib/util.js [hunk 5]
```diff
@@ -27,6 +27,14 @@ function concatJson(resolve, reject) {
   };
 }
 
+function delaysJson(ms, json) {
+  return function (req, res) {
+    setTimeout(function () {
```
Comment (RubenVerborgh) [inline test/lib/util.js]: we do not want an actual timeout; rather, we want to fake time with a timer library somewhere and have timeout values of 5 seconds or so.

File: test/test-with-server.js [hunk 6]
```diff
@@ -235,6 +236,21 @@ describe("follow-redirects", function () {
       });
   });
 
+  it("should callback setTimeout on the returned stream", function () {
+    app.get("/redirect", redirectsTo("/timeout"));
+    app.get("/timeout", delaysJson(5000, { time: "out" }));
```
Comment (RubenVerborgh) [inline test/test-with-server.js]: we should probably have a test where each one is delayed by 1s or so

File: test/test-with-server.js [hunk 7]
```diff
@@ -235,6 +236,21 @@ describe("follow-redirects", function () {
       });
   });
 
+  it("should callback setTimeout on the returned stream", function () {
```
Comment (RubenVerborgh) [inline test/test-with-server.js]: we should also test the case where the timeout limit is not reached

File: test/test-with-server.js [hunk 8]
```diff
@@ -235,6 +236,21 @@ describe("follow-redirects", function () {
...
+    app.get("/redirect", redirectsTo("/timeout"));
+    app.get("/timeout", delaysJson(5000, { time: "out" }));
+
+    return server.start(app)
+      .then(asPromise(function (resolve, reject) {
+        var req = http.get("http://localhost:3600/redirect", reject);
+        req.on("error", reject);
+        req.setTimeout(10, function () {
+          req.abort();
```
Comment (RubenVerborgh) [inline test/test-with-server.js]: But what are we proving if we abort ourselves?

Comment (cavis) [reply test/test-with-server.js]: I don't think the request is actually aborted by the timeout - you have to do that yourself.  So the test suite hangs without this (until it hits the 2000ms limit).

File: test/test-with-server.js (hunk 7 above)
Comment (cavis) [reply test/test-with-server.js]: will do

File: test/test-with-server.js (hunk 6 above)
Comment (cavis) [reply test/test-with-server.js]: +1

File: test/lib/util.js (hunk 5 above)
Comment (cavis) [reply test/lib/util.js]: agreed.  (it's just always a pain to mock http timeouts!)  will see if i can tackle the rest of this with a real-slow test suite, then try to mock out the timers.

File: test/lib/util.js (hunk 4 above)
Comment (cavis) [reply test/lib/util.js]: few more tests to add, so it will be shortly

File: test/test-with-server.js (hunk 8 above)
Comment (cavis) [reply test/test-with-server.js]: Tried this in node 10.7.0 ...

```js
const http = require('http');
const url = 'http://slowwly.robertomurray.co.uk/delay/5000/url/http://www.google.com';

console.log(`GET slow url ->`);
const start = new Date().getTime();
const timer = () => (new Date().getTime() - start) + 'ms';

const req = http.get(url, res => {
  console.log(`  got ${res.statusCode} (${timer()})`);
});
req.on('error', err => {
  console.log(`  got error (${timer()})`, err.message);
});
req.setTimeout(1000, () => {
  // req.abort();
  console.log(`  timeout callback (${timer()})`);
});
process.on('exit', () => {
  console.log(`  exiting (${timer()})`)
});
```

Which prints (with abort commented out vs in):

```
// no abort
GET slow url ->
  timeout callback (1167ms)
  got 302 (5312ms)
  exiting (5316ms)

// with abort()
GET slow url ->
  timeout callback (1185ms)
  got error (1187ms) socket hang up
  exiting (1189ms)
```

File: index.js (hunk 2 above)
Comment (cavis) [reply index.js]: Ahh... okay, I follow now.

File: index.js [hunk 9]
```diff
@@ -147,10 +147,36 @@ RedirectableRequest.prototype.removeHeader = function (name) {
...
+RedirectableRequest.prototype.setTimeout = function (msecs, callback) {
+  if (callback) {
+    this.once("timeout", callback);
+  }
+
+  var self = this;
+  function startTimer() {
+    clearTimeout(self._timeout);
+    self._timeout = setTimeout(function () {
+      self.emit("timeout");
```
Comment (cavis) [inline index.js]: So if I was going to abort the request, I'd put that here.  But since apparently the normal `http#setTimeout` doesn't do that, I opted not to.  Let me know what you think.

Comment (RubenVerborgh) [reply index.js]: You are correct indeed.

File: index.js [hunk 10]
```diff
@@ -147,10 +147,36 @@ RedirectableRequest.prototype.removeHeader = function (name) {
...
+    }, msecs);
+  }
+
+  if (!this.socket) {
+    this._currentRequest.once("socket", function () {
+      startTimer();
+    });
```
Comment (RubenVerborgh) [inline index.js]: you can just `this._currentRequest.once("socket", startTimer)`

**Comment by cavis** [comment]
@RubenVerborgh okay, I've got coverage passing again if you want to take another look.

**Comment by RubenVerborgh** [comment]
Thx for the hard work, will look ASAP.
